### ISSUE TITLE
ICE not setting CORS headers correctly

### ISSUE THREAD

**Issue by nlothian** [oughtinc/ice#121]
Hi, I wanted to try out the [deployed ICE instance](https://ice-80itw1g3n.next.elicit.org/traces/01GCZNZ1YC0XRE1QHSAV6MPWJD) but it doesn't seem to be working. 

I have created https://github.com/oughtinc/ice/pull/122 with an untested possible solution.

**Comment by alexmojaki** [comment]
The official ICE deployment is at https://ice.ought.org/. Where did you get that link from? Also, it's working fine for me.

**Comment by nlothian** [comment]
@alexmojaki thanks!

I got the link here on the front GitHub page:

<img width="302" alt="image" src="https://user-images.githubusercontent.com/117304/205428335-56e217b4-6692-47d8-afa3-2bf47f6ca65c.png">

**Comment by alexmojaki** [comment]
Ah, thanks for pointing that out, I've hidden them now.
