### ISSUE TITLE
Recipe trace page returns {"detail": "Not found"}

### ISSUE THREAD

**Issue by poppingtonic** [oughtinc/ice#154]
I just updated to the latest version (without docker)

After installing the new system in a new virtualenv and checking that my recipes still work with a successful query, I want to go to the trace page and investigate the answers and process, however I get a blank page.

```
Parsed de97451f-8789-4b75-9b39-a1cda44fcae3-InterpretabilityInTheWild.pdf.
Trace: http://localhost:8935/traces/01GM0RQ60TW1QPZA0G1B244N0W            
...
```
![Screenshot from 2022-12-11 17-17-53](https://user-images.githubusercontent.com/5781617/206909029-a65e0c59-9c30-4159-87ab-fd4f56a18ab5.png)

**Comment by lslunis** [comment]
@poppingtonic This is a shot in the dark, but is your old docker container still running?

**Comment by poppingtonic** [comment]
@lslunis The docker container is not running when I try this.

**Comment by lslunis** [comment]
Does the list page at http://localhost:8935/traces/ work, and do any of the traces linked from that page work? You're getting the 404 page for FastAPI, but `ice/routes/app.py` defines a catch-all route, so that shouldn't be possible.

Are you running `python -m ice.server` in a terminal, and if so, is there any logging output?

**Comment by poppingtonic** [comment]
I tried again and got this message
```
ui/index.html not found. Run `npm run build` in the ui directory to create it, or run `npm run dev` to run the dev server and access localhost:5173 instead.
```
The list page at http://localhost:8935/traces/ is blank, and so is the link generated for a single question. They both return a blank page like this:
![Screenshot from 2022-12-17 15-06-08](https://user-images.githubusercontent.com/5781617/208241045-88bb1651-4b7c-4d57-bf71-bb373e520cf9.png)

**Comment by alexmojaki** [comment]
1. Can you try updating your code with the latest from the main branch here?
2. Can you check your browser's developer console for errors?
