### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by amosjyng** [oughtinc/ice#269]
Hey,

I see that ICE seems to be compatible with Python 3.9 and 3.11 now on the master branch. Will there be a new release soon to make this official?

Thanks!

**Comment by lslunis** [comment]
We'll do one this week!

**Comment by amosjyng** [comment]
Awesome, thanks! ☺️

**Comment by lslunis** [comment]
Done: https://pypi.org/project/ought-ice/0.5.0/

**Comment by amosjyng** [comment]
Thank you so much!
