### ISSUE TITLE
Permission denied when trying to enter the container

### ISSUE THREAD

**Issue by DeepVoltaire** [oughtinc/ice#42]
After following the setup, the container is constantly restarting as it hits a permission error. Any ideas what I could try?
![Screenshot from 2022-10-03 10-57-26](https://user-images.githubusercontent.com/15069697/193538953-e2d3e3f0-ae0f-45ed-a094-d164dec9b6e5.png)

**Comment by lslunis** [comment]
I'm investigating this, and hope to have something to report tomorrow morning Pacific time (-0700)

**Comment by lslunis** [comment]
@DeepVoltaire Can you paste the output of `docker version`?

**Comment by DeepVoltaire** [comment]
That's the output from `docker version`
![Screenshot from 2022-10-05 11-14-23](https://user-images.githubusercontent.com/15069697/194025431-2b9234c2-4523-42a5-bf3e-c4b4cbe469a8.png)

I still have the same issue even after trying with the latest changes and also trying to add Alex Hall's suggestion into the dockerfile. I tried cleaning everything up and rebuilding the image with running scripts/run-local.sh, even forcing BUILD=1, but still the same permission denied error.

**Comment by lslunis** [comment]
Try this:

1. change the last line of Dockerfile to `CMD ["sleep", "infinity"]`
2. run `scripts/run-local.sh` in a separate terminal
3. run these commands and paste the output:

```sh
❯ docker compose exec ice bash
root@9c053fe69892:/code# id
uid=0(root) gid=0(root) groups=0(root)
root@9c053fe69892:/code# ls -ld ui
drwxr-xr-x 19 root root 608 Oct  4 16:48 ui
root@9c053fe69892:/code# ls -ld ui/.next
drwxr-xr-x 9 root root 288 Oct  4 21:09 ui/.next
root@9c053fe69892:/code# ls -ld ui/.next/package.json
-rw-r--r-- 1 root root 20 Oct  4 21:09 ui/.next/package.json
```

**Comment by lslunis** [comment]
@DeepVoltaire Since going back and forth once a day will probably be pretty slow, I can pair-debug this with you any time Thursday or Friday: https://notime.zone/NDdd8-ynMUtv-

**Comment by DeepVoltaire** [comment]
Thanks @lslunis I will try to get it to work on Friday and if it's still not working, I will gladly pair-debug with you!

**Comment by DeepVoltaire** [comment]
@lslunis I could not make the time window, sorry!

There is no package.json inside ui/.next/, there is only a package.json inside ui/

```
> docker compose exec ice bash
root@d2a5b4d674d7:/code# id
uid=0(root) gid=0(root) groups=0(root)
root@d2a5b4d674d7:/code# ls -ld ui
drwxrwxr-x 9 1000 1000 4096 Oct  5 08:43 ui
root@d2a5b4d674d7:/code# ls -ld ui/.next
drwxr-xr-x 2 root root 4096 Oct  3 08:38 ui/.next
root@d2a5b4d674d7:/code# ls -ld ui/.next/package.json
ls: cannot access 'ui/.next/package.json': No such file or directory
```

Same error with the most recent master changes.

**Comment by lslunis** [comment]
It looks like ‘ui/‘ isn’t owned by root, and I’m not sure how that’s possible. Are you running the docker daemon as a non-root user?

What happens if you run this?

```sh
ls -lah /code
```

What times are you free? I’m flexible for the next few days.

**Comment by DeepVoltaire** [comment]
I will send you a message on Slack about fixing this live!

I can run "docker run hello-world" without sudo which I assume means I am running it as root. Here is the output of `ls -lah /code` from inside the container
![Screenshot from 2022-10-10 13-34-12](https://user-images.githubusercontent.com/15069697/194857966-68264e6e-de05-44cd-b12c-db9c8f37aa1f.png)

**Comment by lslunis** [comment]
We debugged this in a huddle, and the 1000:1000 ownership is coming from the host system via the volume mount. It’s unclear why this doesn’t affect anyone else using Docker Engine. For reference, this is happening with v2.10.2 of docker compose.

**Comment by lslunis** [comment]
@DeepVoltaire were you able to work around this?

**Comment by DeepVoltaire** [comment]
After installing docker desktop the error remains

![Screenshot from 2022-10-14 10-51-00](https://user-images.githubusercontent.com/15069697/195805472-86b716b5-ae55-4286-b73f-26177748cfb6.png)

The outputs now look like this, the files are now owned by root, but the file `ui/.next/package.json` still does not exist in the container. How should that exist? In the dockerfile I only see `COPY ui/package.json ui/package-lock.json ui/`, but this is only `copying ui/package.json` into `/code/ui/package.json`, right? And then `COPY . .` is copying everything into `/code`, but as there is nothing in `ui/.next` in this repo, nothing will be copied there.

```
> docker compose exec ice bash
root@d2a5b4d674d7:/code# id
uid=0(root) gid=0(root) groups=0(root)
root@d2a5b4d674d7:/code# ls -ld ui
drwxrwxr-x 9 root root 4096 Oct 10 11:11 ui
root@d2a5b4d674d7:/code# ls -ld ui/.next
drwxr-xr-x 2 nobody nogroup 4096 Oct  3 08:38 ui/.next
root@d2a5b4d674d7:/code# ls -ld ui/.next/package.json
ls: cannot access 'ui/.next/package.json': No such file or directory
```

`ls -lah /code `from inside the container
![Screenshot from 2022-10-14 10-49-22](https://user-images.githubusercontent.com/15069697/195804870-4fc415e4-07bc-43fb-98b7-d7fe2afeb3d3.png)

Let's follow up on Slack if you have any other ideas I could try.

**Comment by lslunis** [comment]
I messaged you on Slack

**Comment by DeepVoltaire** [comment]
@lslunis asked me if the `ui/.next/` directory exists on the host, I checked, it did exist and was empty. Probably this prevented that ui/.next/package.json was created in the container. I deleted it with `sudo rm -r ui/.next`, rebuild the image and now everything works. Thank you very much for the help @lslunis !!
