### ISSUE TITLE
Increase in temperature does not seem to induce randomness

### ISSUE THREAD

**Issue by Orowa** [oughtinc/ice#62]
Most likely I have missed something obvious, but I can't seem to induce non-deterministic samples when increasing the temperature parameter.

Reproduction steps:

1. Change [this line](https://github.com/oughtinc/ice/blob/7970c956d7625cf81e2609010e4a1a9c3599c3e5/ice/apis/openai.py#L101) to hardcode `temperature = 1` (you can also create a new OpenAI Agent type with a higher temperature and call it; this is just more direct)
2. Run any simple recipe (for example [question-answering from the primer](https://github.com/oughtinc/ice/blob/main/ice/recipes/primer/qa.py)). 

Expected outcome:

Run 1

![image](https://user-images.githubusercontent.com/34608008/195245047-388e6d61-8cb8-4409-b7c5-751a20a75e2a.png)

Run 2

![image](https://user-images.githubusercontent.com/34608008/195245189-639bbd8c-975c-41bd-8547-d9cda612508d.png)

Actual outcome:

```
root@164d19ecd881:/code# python ./ice/recipes/primer/qa.py 
Trace: http://localhost:3000/traces/01GF5472H56ZJHHFMWJSMZPXCD
A hackathon is happening on 9/9/2022.
root@164d19ecd881:/code# python ./ice/recipes/primer/qa.py 
Trace: http://localhost:3000/traces/01GF5477SGFZ3FTP5KFK0AGH6G
A hackathon is happening on 9/9/2022.
```

**Comment by lslunis** [comment]
@stuhlmueller @reppertj @CG80499 could one of you take a look?

**Comment by reppertj** [comment]
I suspect the local `diskcache` is preventing subsequent calls from actually taking place. The `cache_id` parameter exists to break this cache; if you, e.g., increment this `cache_id` on each call from the agent (e.g. using `itertools.count`), you should get randomness. Alternatively you can remove this cache decorator.

**Comment by Orowa** [comment]
I mean that does work and is straightforward to implement the iterator, though I might argue sampling completions is a primitive enough action that this behaviour might be more easily accessible; YMMV

**Comment by reppertj** [comment]
There are some awkward tradeoffs here re: reproducibility/cost savings to be sure (since the OpenAI API doesn't allow you to parameterize pseudo-randomness in sampling). Depending on the use case, by the way, you could also use the `n` parameter to get multiple samples through a single call.
